# -*- coding: utf-8 -*-
"""Skeleton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EQs9RA3QTd-IWRAqfDN5k7xW65uBwqhv
"""

import matplotlib.pyplot as plt

"""Skeleton Assignment"""

fig=plt.figure()
f1=plt.subplot2grid((5,6),(0,0),rowspan=1,colspan=3)
f2=plt.subplot2grid((5,6),(0,3),rowspan=1,colspan=1)
f3=plt.subplot2grid((5,6),(0,4),rowspan=1,colspan=2)
f4=plt.subplot2grid((5,6),(1,0),rowspan=3)
f5=plt.subplot2grid((5,6),(1,1),rowspan=1,colspan=2)
f6=plt.subplot2grid((5,6),(1,3),rowspan=1,colspan=3)
f7=plt.subplot2grid((5,6),(2,1),rowspan=1,colspan=1)
f8=plt.subplot2grid((5,6),(2,2),rowspan=3,colspan=2)
f9=plt.subplot2grid((5,6),(2,4),rowspan=3,colspan=1)
f10=plt.subplot2grid((5,6),(2,5),rowspan=3,colspan=1)
f11=plt.subplot2grid((5,6),(3,1),rowspan=1,colspan=1)
f9=plt.subplot2grid((5,6),(4,0),rowspan=1,colspan=2)

plt.tight_layout()
plt.show()

